// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: internal/proto/ocr/v1/ocr.proto

package ocrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objectkey     string                 `protobuf:"bytes,1,opt,name=objectkey,proto3" json:"objectkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_internal_proto_ocr_v1_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ocr_v1_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ocr_v1_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetObjectkey() string {
	if x != nil {
		return x.Objectkey
	}
	return ""
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_internal_proto_ocr_v1_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ocr_v1_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_ocr_v1_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_internal_proto_ocr_v1_ocr_proto protoreflect.FileDescriptor

const file_internal_proto_ocr_v1_ocr_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/ocr/v1/ocr.proto\x12\x06ocr.v1\",\n" +
	"\fParseRequest\x12\x1c\n" +
	"\tobjectkey\x18\x01 \x01(\tR\tobjectkey\"#\n" +
	"\rParseResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2D\n" +
	"\n" +
	"OcrService\x126\n" +
	"\aProcess\x12\x14.ocr.v1.ParseRequest\x1a\x15.ocr.v1.ParseResponseB3Z1doc2text/internal/presentation/proto/ocr/v1;ocrv1b\x06proto3"

var (
	file_internal_proto_ocr_v1_ocr_proto_rawDescOnce sync.Once
	file_internal_proto_ocr_v1_ocr_proto_rawDescData []byte
)

func file_internal_proto_ocr_v1_ocr_proto_rawDescGZIP() []byte {
	file_internal_proto_ocr_v1_ocr_proto_rawDescOnce.Do(func() {
		file_internal_proto_ocr_v1_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_ocr_v1_ocr_proto_rawDesc), len(file_internal_proto_ocr_v1_ocr_proto_rawDesc)))
	})
	return file_internal_proto_ocr_v1_ocr_proto_rawDescData
}

var file_internal_proto_ocr_v1_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_ocr_v1_ocr_proto_goTypes = []any{
	(*ParseRequest)(nil),  // 0: ocr.v1.ParseRequest
	(*ParseResponse)(nil), // 1: ocr.v1.ParseResponse
}
var file_internal_proto_ocr_v1_ocr_proto_depIdxs = []int32{
	0, // 0: ocr.v1.OcrService.Process:input_type -> ocr.v1.ParseRequest
	1, // 1: ocr.v1.OcrService.Process:output_type -> ocr.v1.ParseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_ocr_v1_ocr_proto_init() }
func file_internal_proto_ocr_v1_ocr_proto_init() {
	if File_internal_proto_ocr_v1_ocr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_ocr_v1_ocr_proto_rawDesc), len(file_internal_proto_ocr_v1_ocr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_ocr_v1_ocr_proto_goTypes,
		DependencyIndexes: file_internal_proto_ocr_v1_ocr_proto_depIdxs,
		MessageInfos:      file_internal_proto_ocr_v1_ocr_proto_msgTypes,
	}.Build()
	File_internal_proto_ocr_v1_ocr_proto = out.File
	file_internal_proto_ocr_v1_ocr_proto_goTypes = nil
	file_internal_proto_ocr_v1_ocr_proto_depIdxs = nil
}
